// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC18DmagxRsEMzNhchyhUX2DIDGSXl9CO0',
    appId: '1:372365278489:web:a4ceed734d21876be21988',
    messagingSenderId: '372365278489',
    projectId: 'taskflow-cf473',
    authDomain: 'taskflow-cf473.firebaseapp.com',
    storageBucket: 'taskflow-cf473.firebasestorage.app',
    measurementId: 'G-G8NEGEJQ76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJX6_Y-EBIptdzDzKqay4oZBHdLdBgQ0o',
    appId: '1:372365278489:android:98800d14b7b4c173e21988',
    messagingSenderId: '372365278489',
    projectId: 'taskflow-cf473',
    storageBucket: 'taskflow-cf473.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvXuGSS3LunT7dBobGE4bsm_Gu4By3484',
    appId: '1:372365278489:ios:f4d6987e230a03a1e21988',
    messagingSenderId: '372365278489',
    projectId: 'taskflow-cf473',
    storageBucket: 'taskflow-cf473.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvXuGSS3LunT7dBobGE4bsm_Gu4By3484',
    appId: '1:372365278489:ios:f4d6987e230a03a1e21988',
    messagingSenderId: '372365278489',
    projectId: 'taskflow-cf473',
    storageBucket: 'taskflow-cf473.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC18DmagxRsEMzNhchyhUX2DIDGSXl9CO0',
    appId: '1:372365278489:web:a1140f6aac1f216ce21988',
    messagingSenderId: '372365278489',
    projectId: 'taskflow-cf473',
    authDomain: 'taskflow-cf473.firebaseapp.com',
    storageBucket: 'taskflow-cf473.firebasestorage.app',
    measurementId: 'G-PQM5XF4YZH',
  );
}
